// Material UI enhanced components
export { MaterialButton as Button } from './MaterialButton';

// Re-export Material UI components with enhanced styling
export {
  Card,
  CardContent,
  CardActions,
  CardHeader,
  CardMedia,
  Typography,
  Box,
  Container,
  Grid,
  Stack,
  Paper,
  Chip,
  Avatar,
  Badge,
  Divider,
  Fab,
  IconButton,
  Tooltip,
  AppBar,
  Toolbar,
  Drawer,
  List,
  ListItem,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  Menu,
  MenuItem,
  Snackbar,
  Alert,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  Select,
  FormControl,
  InputLabel,
  Checkbox,
  Switch,
  Radio,
  RadioGroup,
  FormControlLabel,
  Slider,
  Tab,
  Tabs,
  TabPanel,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Breadcrumbs,
  Pagination,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  CircularProgress,
  LinearProgress,
  Skeleton,
} from '@mui/material';

// Re-export Material UI icons
export * from '@mui/icons-material';
